### ISSUE TITLE
Switch from netty to tomcat

### ISSUE THREAD

**Issue by CaledoniaProject** [wdahlenburg/spring-gateway-demo#2]
How can I change the embedded server from netty to tomcat?

**Comment by wdahlenburg** [comment]
Hi @CaledoniaProject. The gateway server (managed by the actuator) and the gateway client (which proxies the requests) are defined in the [spring-cloud-gateway-server](https://github.com/spring-cloud/spring-cloud-gateway/tree/main/spring-cloud-gateway-server) library.

I don't think it would be an easy switch to convert that libraries' server to tomcat.

A more common use case of an API may use a default spring app to serve a few endpoints. You could use any web server to manage this. The gateway server could then be enabled to add additional routes or handle additional protocols like websockets.
